version: '3.4'

volumes:
  l2_data:

services:
  l2:
    image: ghcr.io/celestiaorg/nitro:v3.5.2
    platform: linux/amd64
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "${PWD}/nodeConfig.json:/config/nodeConfig.json"
      - l2_data:/home/user/.arbitrum
    entrypoint:
      - "/usr/local/bin/nitro"
      - --conf.file=/config/nodeConfig.json
      - --node.staker.enable
      - --node.staker.strategy=Watchtower
      - --execution.forwarding-target=wss://toii-testnet.rpc.caldera.xyz/ws
      - --node.feed.input.url=wss://toii-testnet.rpc.caldera.xyz/feed
      - --parent-chain.connection.url=
      
      
